version: "2"

services:
  postgresdb:
    image: postgres:9.6
    container_name: "postgres"
    networks:
      - postgresdbnet
    environment:
      - POSTGRES_DB=dollardb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
    volumes:
      - ./volumes/postgresData:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin2020"
    ports:
      - "6543:80"
    depends_on:
      - postgresdb
    networks:
      - postgresdbnet

networks:
  postgresdbnet:
    driver: bridge